export const SEARCH_MOVIES_SUCCESS = 'SEARCH_MOVIES_SUCCESS';
export const SEARCH_MOVIES_FAILURE = 'SEARCH_MOVIES_FAILURE';
export const SELECTED_MOVIE_DETAILS = 'SELECTED_MOVIE_DETAILS';
export const SELECTED_TIMINGS_DETAILS = 'SELECTED_TIMINGS_DETAILS';
